global using Arc.CustomApp.Application.Behaviors;
global using Arc.CustomApp.Application.Queries;
global using Arc.CustomApp.Infra;
global using FluentValidation;
global using FluentValidation.Results;
global using MediatR;
global using Moq;
global using Shouldly;
global using Xunit;
