name: build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  config: release

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: restore nuget packages
      run: dotnet restore --locked-mode

    - name: build
      run: dotnet build -c ${{ env.config }} --no-restore

    - name: test
      run: dotnet test -c ${{ env.config }} --no-build